=== tuwiendsg/COMOT/comot-fluent-api/comot-fluent-platform/src/main/resources/compositionRules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

 
  <xs:element name="CompositionOperationType" type="compositionOperationType"/>

  <xs:element name="CompositionRule" type="compositionRule"/>

  <xs:element name="CompositionRulesConfiguration" type="compositionRulesConfiguration"/>

  <xs:element name="Metric" nillable="true" type="xs:anyType"/>

  <xs:element name="MetricValue" type="metricValue"/>

  <xs:element name="MetricsCompositionRules" type="compositionRulesBlock"/>

  <xs:element name="MonitoredElement" type="monitoredElement"/>

  <xs:element name="MonitoredElementLevel" type="monitoredElementLevel"/>
 
  <xs:element name="Operation" type="compositionOperation"/>

    
  <xs:complexType name="monitoredElement">
    <xs:sequence>
      <xs:element ref="MonitoredElement" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="level" type="monitoredElementLevel" use="required"/>
  </xs:complexType>

   

  <xs:complexType name="metric">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="measurementUnit" type="xs:string" use="required"/>
    <xs:attribute name="type" type="metricType" use="required"/>
  </xs:complexType>

   
  
  <xs:complexType name="compositionOperation">
    <xs:sequence>
      <xs:element name="ReferenceMetric" type="metric" minOccurs="0"/>
      <xs:element name="SourceMonitoredElementID" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="Operation" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="compositionOperationType" use="required"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="MetricSourceMonitoredElementLevel" type="monitoredElementLevel" use="required"/>
  </xs:complexType>

  <xs:complexType name="monitoringEntriesAdapter">
    <xs:complexContent>
      <xs:extension base="xmlAdapter">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="xmlAdapter" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="myIterator">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="applicationComponentIterator">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="compositionRule">
    <xs:sequence>
      <xs:element name="TargetMonitoredElementID" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ResultingMetric" type="metric"/>
      <xs:element ref="Operation"/>
    </xs:sequence>
    <xs:attribute name="TargetMonitoredElementLevel" type="monitoredElementLevel" use="required"/>
  </xs:complexType>

  <xs:complexType name="compositionRulesConfiguration">
    <xs:sequence>
      <xs:element ref="MetricsCompositionRules" minOccurs="0"/>
      <xs:element name="HistoricalMetricsCompositionRules" type="compositionRulesBlock" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="TargetServiceID" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="compositionRulesBlock">
    <xs:sequence>
      <xs:element ref="CompositionRule" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="monitoredElementLevel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SERVICE"/>
      <xs:enumeration value="SERVICE_TOPOLOGY"/>
      <xs:enumeration value="SERVICE_UNIT"/>
      <xs:enumeration value="VM"/>
      <xs:enumeration value="VIRTUAL_CLUSTER"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="metricType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RESOURCE"/>
      <xs:enumeration value="COST"/>
      <xs:enumeration value="QUALITY"/>
      <xs:enumeration value="ELASTICITY"/>
    </xs:restriction>
  </xs:simpleType>

   

  <xs:simpleType name="compositionOperationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SUM"/>
      <xs:enumeration value="MAX"/>
      <xs:enumeration value="MIN"/>
      <xs:enumeration value="AVG"/>
      <xs:enumeration value="DIV"/>
      <xs:enumeration value="ADD"/>
      <xs:enumeration value="SUB"/>
      <xs:enumeration value="MUL"/>
      <xs:enumeration value="CONCAT"/>
      <xs:enumeration value="UNION"/>
      <xs:enumeration value="KEEP"/>
      <xs:enumeration value="KEEP_LAST"/>
      <xs:enumeration value="KEEP_FIRST"/>
      <xs:enumeration value="SET_VALUE"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== tuwiendsg/COMOT/comot-fluent-api/comot-fluent-platform/src/main/resources/compositionRules.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CompositionRulesConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="compositionRules.xsd">
    
    <MetricsCompositionRules>
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="no" name="activeConnections"/>
            <Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
                <ReferenceMetric type="RESOURCE" name="activeConnections"/>
            </Operation>
        </CompositionRule>
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            
            <ResultingMetric type="RESOURCE" measurementUnit="%" name="cpuUsage"/>
            <Operation value="100" type="ADD">
                  <Operation value="-1" type="MUL">
                         <Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
                   		 <ReferenceMetric type="RESOURCE" measurementUnit="%"  name="cpu_idle"/>
                </Operation>
            </Operation>
            </Operation>
        </CompositionRule>
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="%" name="cpuUsage"/>
            <Operation value="100" type="ADD">
                  <Operation value="-1" type="MUL">
                         <Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
                   		 <ReferenceMetric type="RESOURCE" measurementUnit="%" name="cpu_idle"/>
                </Operation>
            </Operation>
            </Operation>
        </CompositionRule>
      
            
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="ms" name="responseTime"/>
            <Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
                <ReferenceMetric type="RESOURCE" name="responseTime"/>
            </Operation>
        </CompositionRule>

 
    	 <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
			<ResultingMetric type="RESOURCE" measurementUnit="ms" name="latency" />
			<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
				<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
					<ReferenceMetric type="RESOURCE" name="read_latency" />
				</Operation>
				<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
					<ReferenceMetric type="RESOURCE" name="write_latency" />
				</Operation>
			</Operation>
			</CompositionRule>
			<CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
				<ResultingMetric type="RESOURCE" measurementUnit="ms" name="latency" />
				<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
					<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
						<ReferenceMetric type="RESOURCE" name="read_latency" />
					</Operation>
					<Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
						<ReferenceMetric type="RESOURCE" name="write_latency" />
					</Operation>
				</Operation>
			</CompositionRule>
 
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="operations/s" name="throughput"/>
            <Operation MetricSourceMonitoredElementLevel="VM" type="SUM">
                <ReferenceMetric type="RESOURCE" name="throughput"/>
             </Operation>
        </CompositionRule>
        
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric name="avgThroughput" measurementUnit="operations/s" type="QUALITY"/>
             <Operation MetricSourceMonitoredElementLevel="VM" type="AVG">
                <ReferenceMetric type="RESOURCE" name="throughput"/>
             </Operation>
        </CompositionRule>
        
     
         <CompositionRule TargetMonitoredElementLevel="VM">
            <ResultingMetric type="RESOURCE" measurementUnit="ms" name="numberOfVMs"/>
            <Operation value="1" type="SET_VALUE"/>
        </CompositionRule>

 
        <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="ms" name="numberOfVMs"/>
            <Operation MetricSourceMonitoredElementLevel="VM" type="SUM">
                <ReferenceMetric type="RESOURCE" name="numberOfVMs"/>
            </Operation>
        </CompositionRule>

       <CompositionRule TargetMonitoredElementLevel="SERVICE_UNIT">
            <ResultingMetric type="RESOURCE" measurementUnit="$" name="cost"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" value="0.12" type="MUL">
			       <ReferenceMetric type="RESOURCE" name="numberOfVMs"/>
            </Operation>
        </CompositionRule>
 
        
         <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="QUALITY" measurementUnit="ms" name="latency"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="KEEP">
                <ReferenceMetric type="QUALITY" measurementUnit="ms" name="latency"/>
            </Operation>
        </CompositionRule>
         <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="RESOURCE" measurementUnit="%" name="cpuUsage"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="AVG">
                <ReferenceMetric type="RESOURCE" measurementUnit="%" name="cpuUsage"/>
            </Operation>
        </CompositionRule>
        <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="RESOURCE" measurementUnit="ms" name="responseTime"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="AVG">
                <ReferenceMetric type="RESOURCE" name="responseTime"/>
            </Operation>
        </CompositionRule>
        <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="RESOURCE" measurementUnit="operations/s" name="throughput"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="SUM">
                <ReferenceMetric type="RESOURCE" name="throughput"/>
            </Operation>
        </CompositionRule>
        
        
        <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="RESOURCE" measurementUnit="operations/s" name="avgThroughput"/>
            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="SUM">
                <ReferenceMetric type="RESOURCE" name="avgThroughput"/>
            </Operation>
        </CompositionRule>
        
        
        
        
        
        <CompositionRule TargetMonitoredElementLevel="SERVICE_TOPOLOGY">
            <ResultingMetric type="RESOURCE" measurementUnit="$/h" name="cost"/>
                <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="SUM">
                    <ReferenceMetric type="COST" name="cost"/>
                </Operation>
        </CompositionRule>

          <CompositionRule TargetMonitoredElementLevel="SERVICE">
            <Operation type="MUL">
                    <Operation type="DIV">
		           <Operation MetricSourceMonitoredElementLevel="SERVICE_TOPOLOGY" type="SUM">
		               <ReferenceMetric type="COST" measurementUnit="$/h" name="cost"/>
		           </Operation>
	 
		            <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="KEEP">
		               <ReferenceMetric type="RESOURCE" measurementUnit="operations/s" name="throughput"/>
		            </Operation>
                       
                    </Operation>
                    <Operation MetricSourceMonitoredElementLevel="SERVICE_UNIT" type="DIV">
                       <Operation value="1000" type="SET_VALUE"/>   
                       <Operation value="360" type="SET_VALUE"/>   
                    </Operation>   
                 </Operation>   
                <ResultingMetric type="COST" measurementUnit="$/1000ops" name="cost"/>

        </CompositionRule>

    </MetricsCompositionRules>
     
</CompositionRulesConfiguration>
